# This is the configuration file for catnip.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnip

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username = {icon = " ", name = "user", color = "(RD)"}
hostname = {icon = " ", name = "hostname", color = "(YW)"}
uptime   = {icon = " ", name = "uptime", color = "(BE)"}
distro   = {icon = " ", name = "distro", color = "(GN)"}
kernel   = {icon = " ", name = "kernel", color = "(MA)"}
desktop  = {icon = " ", name = "desktop", color = "(CN)"}
terminal = {icon = " ", name = "term", color = "(RD)"}
shell    = {icon = " ", name = "shell", color = "(MA)"}
# cpu      = {icon = " ", name = "cpu", color = "(RD)"}
# disk     = {icon = " ", name = "disk", color = "(GN)"}
memory   = {icon = " ", name = "memory", color = "(YW)"}
colors   = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]

[misc.figletLogos]
enable = false
color  = "(CN)"
font   = "slant"
margin = [0, 0, 0,]
