#!/bin/bash

# Define the file name
file="$HOME/.config/hypr/hyprland.conf"

# Check if lines 8 to 12 already contain '#'
if ! sed -n '9,13 { /^#/!q1 }' "$file" &> /dev/null; then
    # Add '#' to lines that don't have '#'
    sed -i '9,13 { /^[^#]/s/^/#/ }' "$file" 
    # Remove '#' from lines 9 and 13
    sed -i '9s/^#//' "$file" 
    sed -i '13s/^#//' "$file"
else
    dunstify "hyprscreen is already active"
fi
